apiVersion: v1
kind: Service
metadata:
  name: micro-sample
  labels:
    run: micro-sample
spec:
  ports:
  - port: 80
    protocol: TCP
    name: micro-samlpe-service
  selector:
    run: micro-sample
  type: LoadBalancer